export enum FormInfo {
  contactInfo = 'Contact Info',
  createdAt = 'Created At',
  divisionsName = 'Divisions Name',
  flowStatus = 'Approval Status',
  phone = 'Phone',
  recipient = 'Recipient',
  shipTo = 'Ship To',
  shipment = 'Shipment',
  srName = 'Sr Name',
  stockLocName = 'StockLocName',
  deliveryDate = 'Delivery Date',

  // my task & my request (shipTo, recipient, phone repeated with the above)
  sr = 'SR',
  status = 'Approval Status',
  stockLocation = 'Stock Location',
  requestType = 'Request',
  requestor = 'Requestor',
  requestDate = 'Request Date',
  orderNumber = 'MyOrder No.',
  pendingBy = 'Pending Approval By',
  soldTo = 'Sold To',
  accountName = 'Account Name',
  division = 'Division',
  orderNo = 'MyOrder No.',
  orderType = 'Order Type',
  submittedBy = 'Submitted By',
  submittedDate = 'Submitted Date/Time',
}
